'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AppLog
    Public Property LogID As Integer
    Public Property EID As Integer
    Public Property LogType As String
    Public Property DateTime As Date
    Public Property Message As String

End Class
