'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property EID As Integer
    Public Property Username As String
    Public Property NameFirst As String
    Public Property NameLast As String
    Public Property NameMiddle As String
    Public Property SSN As String
    Public Property AddressHome As String
    Public Property CityHome As String
    Public Property StateHome As String
    Public Property ZipHome As String
    Public Property PhoneHome As String
    Public Property PhoneCell As String
    Public Property DOB As Date
    Public Property DL As String
    Public Property MaritalStatus As String
    Public Property DateStarted As Date
    Public Property Email As String
    Public Property Password As String
    Public Property Salt As String
    Public Property AccessLevel As Integer
    Public Property AccountLocked As Boolean
    Public Property ForcePasswordChange As Boolean
    Public Property EmergencyContactName As String
    Public Property EmergencyContactPhone1 As String
    Public Property EmergencyContactPhone2 As String
    Public Property Active As Boolean

End Class
